sandbox: handle /opt/local on separate mountpoint
macports/macports-base pull request #208
Opened 2020-08-31 11:00 UTC by danchr

Some Xcode builds will fail when /opt is on a separate volume. The nature of the errors vary, for example `tiffutil` will frequently fail. They're all permission-related errors, though.

Looking at the system logs, I noticed this:

```
localhost kernel[0]: (Sandbox) Sandbox: tiffutil(99434) deny(1) file-write-create /opt/.TemporaryItems/folders.502/TemporaryItems/(A Document Being Saved By tiffutil)
```

To address this, I added some code that should detect the mountpoint for `${prefix}`, and add its `.TemporaryItems` to the allowed directories.

2020-08-31 11:14 UTC, danchr commented
See also https://github.com/macports/macports-ports/pull/8244 — that's where I ran into this, and it contains some relevant log messages.

2020-09-01 13:56 UTC, neverpanic requested changes
A small nitpick, other than that this lg2m.

2020-09-01 13:56 UTC, neverpanic commented on src/port1.0/portutil.tcl
> +    while {$parentdir != "/"} {
```suggestion
    while {$parentdir ne "/"} {
```

In Tcl, "eq" and "ne" perform string comparisons, while "==" and "!=" attempt to perform integer comparisons first and then fall back to string comparisons.

2020-09-14 19:08 UTC, neverpanic approved these changes

2020-09-14 19:08 UTC, neverpanic commented
Actually, could you please squash this so I can rebase the changes?

2020-09-14 19:47 UTC, danchr commented
> Actually, could you please squash this so I can rebase the changes?

Squashed and rebased!

2020-09-17 20:47 UTC, neverpanic approved these changes

2020-09-17 20:47 UTC, merged